resources:
  - name: sources
    type: git
    source:
      uri: https://github.com/riteshbabu/concourse-demo.git
      branch: master

jobs:
- name: test
  plan:
  - get: sources
    trigger: true
  - task: install
    file: sources/pipeline/install.yml
  - task: test
    file: sources/pipeline/test.yml